### ISSUE TITLE
Error in adding entities

### ISSUE THREAD

**Issue by rotherpawel** [pawelhulek/pgnig-sensor#41]
Cześć,
Ustawiłem integrację jak w opisie, ale w logach widzę takie errory jak poniżej. Nie wczytują się encje z sensor.pgnig_gas_cost_tracking_sensor:

`2022-09-07 15:10:09.307 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform pgnig_gas_sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 673, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
state = self._stringify_state(available)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
if (state := self.state) is None:
File "/config/custom_components/pgnig_gas_sensor/sensor.py", line 224, in state
return self._state.gross_amount / self._state.wear
TypeError: unsupported operand type(s) for /: 'NoneType' and 'NoneType'`

**Comment by MarcinJanCiesielski** [comment]
Potwierdzam problem:

Logger: homeassistant.components.sensor
Source: custom_components/pgnig_gas_sensor/sensor.py:224
Integration: Sensor (documentation, issues)
First occurred: 21:37:12 (2 occurrences)
Last logged: 21:37:12

Error adding entities for domain sensor with platform pgnig_gas_sensor
Error while setting up pgnig_gas_sensor platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 673, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 777, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/pgnig_gas_sensor/sensor.py", line 224, in state
    return self._state.gross_amount / self._state.wear
TypeError: unsupported operand type(s) for /: 'NoneType' and 'NoneType'


Wersja PGNIG Sensor: v2.3.3
Wersja Home Assistant: 2022.8 oraz 2022.9

**Comment by pawelhulek** [comment]
Dorzuce filtrowanie faktur po pustych wartosciach gross_amount i wear? Ale mozecie jeszcze dac znac co to za faktura jest ze nie ma kwoty brutto do zaplaty ani ilosci zuzytego gazu?

**Comment by rotherpawel** [comment]
Tzn moja to akurat jakaś nota odsetkowa na 2 grosze 😂. Ale faktycznie bez żadnego zużycia.

**Comment by MarcinJanCiesielski** [comment]
U mnie akurat żadnej faktury nie ma (ostatnią zapłaciłem, a nowego odczytu i prognoz jeszcze nie ma).
Natomiast przy poprzedniej wersji PGNiG Sensor była analogiczna sytuacja a problem z dodaniem encji nie występował.

**Comment by pawelhulek** [comment]
Sprawdzicie na nowej becie, prosze? v2.3.4 - w kanale Beta

**Comment by MarcinJanCiesielski** [comment]
Sprawdziłem betę. Błąd o braku możliwości dodania encji przestał występować, natomiast encja sensor.pgnig_gas_cost_tracking_sensor nie jest tworzona.

**Comment by pawelhulek** [comment]
Dla faktur odsetkowych nie bedzie tworzona. W nastepnym miesiacu powinno sie stworzyc juz dobrze.
