### ISSUE TITLE
Error while setting up pgnig_gas_sensor platform

### ISSUE THREAD

**Issue by MG-Sky** [pawelhulek/pgnig-sensor#44]
hi, below entity fails: (no price for gas)

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 673, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 777, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
state = self._stringify_state(available)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
if (state := self.state) is None:
File "/config/custom_components/pgnig_gas_sensor/sensor.py", line 224, in state
return self._state.gross_amount / self._state.wear
TypeError: unsupported operand type(s) for /: 'NoneType' and 'NoneType'

**Comment by baterja** [comment]
Z tego co widzę to w wersji 2.3.4 jest już to naprawione, ale ta wersja nie została jeszcze zreleasowana.

**Comment by pawelhulek** [comment]
I don't think 2.3.4 will help - I will need to take a closer look, but don't have much time recently ;/ Will try to tackle this one this week

**Comment by baterja** [comment]
Btw. look what I've found in the response while browsing their eBok website:
![obraz](https://user-images.githubusercontent.com/12954147/193227546-a8bd7db6-59ff-4d5d-8d2a-f8d8f4003361.png)
Are they tracking your integration or preparing their own? :)

I've downloaded the repository and I think the issue might be that `Wear` is used (which is 0 in my case) instead of `WearKWH`. I've only checked it out briefly though.

**Comment by pawelhulek** [comment]
@baterja Can you provide response - obfuscated obviously or with data changed. I am intersted what is empty and was is not - you can change numbers sligthly

**Comment by pawelhulek** [comment]
@baterja @MG-Sky The problem is quite complex. You probably don't have access to m3 usage data in the invoice :/ Please check - https://github.com/pawelhulek/pgnig-sensor/issues/43#issuecomment-1263845011

**Comment by baterja** [comment]
@pawelhulek Ależ proszę:
```json
{
    "HasNonPaidForecast": false,
    "AllowLoadAfter30Days": false,
    "InvoicesList": [
        {
            "Number": "1234567/20/2021/F",
            "Date": "2021-11-09T00:00:00.000000Z",
            "SellDate": "2022-09-08T00:00:00.000000Z",
            "GrossAmount": 21.37,
            "AmountToPay": 0.0,
            "Wear": 0.0,
            "WearKWH": 22.0,
            "PayingDeadlineDate": "2022-09-22T00:00:00.000000Z",
            "StartDate": "2022-07-08T00:00:00.000000Z",
            "EndDate": "2022-09-30T00:00:00.000000Z",
            "IsPaid": true,
            "IdPP": "1234567",
            "Type": "PPG",
            "TempType": "B",
            "DaysRemainingToDeadline": 0,
            "HasIban": true,
            "Iban": "ban",
            "Status": "Posted",
            "PdfExists": false,
            "IsInterestNote": false,
            "Color": "",
            "AgreementName": "",
            "AgreementNumber": "000/1990/00000/XX",
            "IsAdditionalAgreement": false,
            "AgreementEndDate": null,
            "AgreementExpired": false,
            "PDFPrintAllowed": true,
            "PaymentProcessAllowed": true,
            "AgreementHasCard": false,
            "AutomaticPaymentDate": "2022-09-20T00:00:00.000000Z",
            "IsInsurancePolicy": false,
            "IsLawyerAgreement": false,
            "IsPersonalSecurityAgreement": false
        },
        {
            "Number": "1234567/19/2021/F",
            "Date": "2021-11-09T00:00:00.000000Z",
            "SellDate": "2022-07-08T00:00:00.000000Z",
            "GrossAmount": 21.37,
            "AmountToPay": 0.0,
            "Wear": 0.0,
            "WearKWH": 22.0,
            "PayingDeadlineDate": "2022-07-22T00:00:00.000000Z",
            "StartDate": "2022-05-08T00:00:00.000000Z",
            "EndDate": "2022-07-31T00:00:00.000000Z",
            "IsPaid": true,
            "IdPP": "1234567",
            "Type": "PPG",
            "TempType": "B",
            "DaysRemainingToDeadline": 0,
            "HasIban": true,
            "Iban": "ban",
            "Status": "Posted",
            "PdfExists": false,
            "IsInterestNote": false,
            "Color": "",
            "AgreementName": "",
            "AgreementNumber": "000/1990/00000/XX",
            "IsAdditionalAgreement": false,
            "AgreementEndDate": null,
            "AgreementExpired": false,
            "PDFPrintAllowed": true,
            "PaymentProcessAllowed": true,
            "AgreementHasCard": false,
            "AutomaticPaymentDate": "2022-07-20T00:00:00.000000Z",
            "IsInsurancePolicy": false,
            "IsLawyerAgreement": false,
            "IsPersonalSecurityAgreement": false
        },
        {
            "Number": "1234567/18/2021/F",
            "Date": "2021-11-09T00:00:00.000000Z",
            "SellDate": "2022-05-08T00:00:00.000000Z",
            "GrossAmount": 21.37,
            "AmountToPay": 0.0,
            "Wear": 0.0,
            "WearKWH": 22.0,
            "PayingDeadlineDate": "2022-05-23T00:00:00.000000Z",
            "StartDate": "2022-03-08T00:00:00.000000Z",
            "EndDate": "2022-05-31T00:00:00.000000Z",
            "IsPaid": true,
            "IdPP": "1234567",
            "Type": "PPG",
            "TempType": "B",
            "DaysRemainingToDeadline": 0,
            "HasIban": true,
            "Iban": "ban",
            "Status": "Posted",
            "PdfExists": false,
            "IsInterestNote": false,
            "Color": "",
            "AgreementName": "",
            "AgreementNumber": "000/1990/00000/XX",
            "IsAdditionalAgreement": false,
            "AgreementEndDate": null,
            "AgreementExpired": false,
            "PDFPrintAllowed": true,
            "PaymentProcessAllowed": true,
            "AgreementHasCard": false,
            "AutomaticPaymentDate": "2022-05-21T00:00:00.000000Z",
            "IsInsurancePolicy": false,
            "IsLawyerAgreement": false,
            "IsPersonalSecurityAgreement": false
        },
        {
            "Number": "1234567/17/2021/F",
            "Date": "2021-11-09T00:00:00.000000Z",
            "SellDate": "2022-03-08T00:00:00.000000Z",
            "GrossAmount": 21.37,
            "AmountToPay": 0.0,
            "Wear": 0.0,
            "WearKWH": 22.0,
            "PayingDeadlineDate": "2022-03-22T00:00:00.000000Z",
            "StartDate": "2022-01-08T00:00:00.000000Z",
            "EndDate": "2022-03-31T00:00:00.000000Z",
            "IsPaid": true,
            "IdPP": "1234567",
            "Type": "PPG",
            "TempType": "B",
            "DaysRemainingToDeadline": 0,
            "HasIban": true,
            "Iban": "ban",
            "Status": "Posted",
            "PdfExists": false,
            "IsInterestNote": false,
            "Color": "",
            "AgreementName": "",
            "AgreementNumber": "000/1990/00000/XX",
            "IsAdditionalAgreement": false,
            "AgreementEndDate": null,
            "AgreementExpired": false,
            "PDFPrintAllowed": true,
            "PaymentProcessAllowed": true,
            "AgreementHasCard": false,
            "AutomaticPaymentDate": "2022-03-20T00:00:00.000000Z",
            "IsInsurancePolicy": false,
            "IsLawyerAgreement": false,
            "IsPersonalSecurityAgreement": false
        },
        {
            "Number": "1234567/16/2021/F",
            "Date": "2021-11-09T00:00:00.000000Z",
            "SellDate": "2022-01-08T00:00:00.000000Z",
            "GrossAmount": 21.37,
            "AmountToPay": 0.0,
            "Wear": 0.0,
            "WearKWH": 22.0,
            "PayingDeadlineDate": "2022-01-24T00:00:00.000000Z",
            "StartDate": "2021-11-08T00:00:00.000000Z",
            "EndDate": "2022-01-31T00:00:00.000000Z",
            "IsPaid": true,
            "IdPP": "1234567",
            "Type": "PPG",
            "TempType": "B",
            "DaysRemainingToDeadline": 0,
            "HasIban": true,
            "Iban": "ban",
            "Status": "Posted",
            "PdfExists": false,
            "IsInterestNote": false,
            "Color": "",
            "AgreementName": "",
            "AgreementNumber": "000/1990/00000/XX",
            "IsAdditionalAgreement": false,
            "AgreementEndDate": null,
            "AgreementExpired": false,
            "PDFPrintAllowed": true,
            "PaymentProcessAllowed": true,
            "AgreementHasCard": false,
            "AutomaticPaymentDate": "2022-01-22T00:00:00.000000Z",
            "IsInsurancePolicy": false,
            "IsLawyerAgreement": false,
            "IsPersonalSecurityAgreement": false
        },
        {
            "Number": "1234567/15/2021/F",
            "Date": "2021-11-09T00:00:00.000000Z",
            "SellDate": "2021-11-08T00:00:00.000000Z",
            "GrossAmount": 10.48,
            "AmountToPay": 0.0,
            "Wear": 0.0,
            "WearKWH": 115.0,
            "PayingDeadlineDate": "2021-11-23T00:00:00.000000Z",
            "StartDate": "2020-11-23T00:00:00.000000Z",
            "EndDate": "2021-11-30T00:00:00.000000Z",
            "IsPaid": true,
            "IdPP": "1234567",
            "Type": "PPG",
            "TempType": "R",
            "DaysRemainingToDeadline": 0,
            "HasIban": true,
            "Iban": "ban",
            "Status": "Posted",
            "PdfExists": false,
            "IsInterestNote": false,
            "Color": "",
            "AgreementName": "",
            "AgreementNumber": "000/1990/00000/XX",
            "IsAdditionalAgreement": false,
            "AgreementEndDate": null,
            "AgreementExpired": false,
            "PDFPrintAllowed": true,
            "PaymentProcessAllowed": true,
            "AgreementHasCard": false,
            "AutomaticPaymentDate": "2021-11-21T00:00:00.000000Z",
            "IsInsurancePolicy": false,
            "IsLawyerAgreement": false,
            "IsPersonalSecurityAgreement": false
        },
        {
            "Number": "1234567/14/2020/F",
            "Date": "2020-11-24T00:00:00.000000Z",
            "SellDate": "2021-09-23T00:00:00.000000Z",
            "GrossAmount": 22.34,
            "AmountToPay": 0.0,
            "Wear": 0.0,
            "WearKWH": 33.0,
            "PayingDeadlineDate": "2021-10-07T00:00:00.000000Z",
            "StartDate": "2021-07-23T00:00:00.000000Z",
            "EndDate": "2021-09-30T00:00:00.000000Z",
            "IsPaid": true,
            "IdPP": "1234567",
            "Type": "PPG",
            "TempType": "B",
            "DaysRemainingToDeadline": 0,
            "HasIban": true,
            "Iban": "ban",
            "Status": "Posted",
            "PdfExists": false,
            "IsInterestNote": false,
            "Color": "",
            "AgreementName": "",
            "AgreementNumber": "000/1990/00000/XX",
            "IsAdditionalAgreement": false,
            "AgreementEndDate": null,
            "AgreementExpired": false,
            "PDFPrintAllowed": true,
            "PaymentProcessAllowed": true,
            "AgreementHasCard": false,
            "AutomaticPaymentDate": "2021-10-05T00:00:00.000000Z",
            "IsInsurancePolicy": false,
            "IsLawyerAgreement": false,
            "IsPersonalSecurityAgreement": false
        },
        {
            "Number": "1234567/13/2020/F",
            "Date": "2020-11-24T00:00:00.000000Z",
            "SellDate": "2021-07-23T00:00:00.000000Z",
            "GrossAmount": 22.34,
            "AmountToPay": 0.0,
            "Wear": 0.0,
            "WearKWH": 33.0,
            "PayingDeadlineDate": "2021-08-06T00:00:00.000000Z",
            "StartDate": "2021-05-23T00:00:00.000000Z",
            "EndDate": "2021-07-31T00:00:00.000000Z",
            "IsPaid": true,
            "IdPP": "1234567",
            "Type": "PPG",
            "TempType": "B",
            "DaysRemainingToDeadline": 0,
            "HasIban": true,
            "Iban": "ban",
            "Status": "Posted",
            "PdfExists": false,
            "IsInterestNote": false,
            "Color": "",
            "AgreementName": "",
            "AgreementNumber": "000/1990/00000/XX",
            "IsAdditionalAgreement": false,
            "AgreementEndDate": null,
            "AgreementExpired": false,
            "PDFPrintAllowed": true,
            "PaymentProcessAllowed": true,
            "AgreementHasCard": false,
            "AutomaticPaymentDate": "2021-08-04T00:00:00.000000Z",
            "IsInsurancePolicy": false,
            "IsLawyerAgreement": false,
            "IsPersonalSecurityAgreement": false
        },
        {
            "Number": "1234567/12/2020/F",
            "Date": "2020-11-24T00:00:00.000000Z",
            "SellDate": "2021-05-23T00:00:00.000000Z",
            "GrossAmount": 22.34,
            "AmountToPay": 0.0,
            "Wear": 0.0,
            "WearKWH": 33.0,
            "PayingDeadlineDate": "2021-06-07T00:00:00.000000Z",
            "StartDate": "2021-03-23T00:00:00.000000Z",
            "EndDate": "2021-05-31T00:00:00.000000Z",
            "IsPaid": true,
            "IdPP": "1234567",
            "Type": "PPG",
            "TempType": "B",
            "DaysRemainingToDeadline": 0,
            "HasIban": true,
            "Iban": "ban",
            "Status": "Posted",
            "PdfExists": false,
            "IsInterestNote": false,
            "Color": "",
            "AgreementName": "",
            "AgreementNumber": "000/1990/00000/XX",
            "IsAdditionalAgreement": false,
            "AgreementEndDate": null,
            "AgreementExpired": false,
            "PDFPrintAllowed": true,
            "PaymentProcessAllowed": true,
            "AgreementHasCard": false,
            "AutomaticPaymentDate": "2021-06-05T00:00:00.000000Z",
            "IsInsurancePolicy": false,
            "IsLawyerAgreement": false,
            "IsPersonalSecurityAgreement": false
        },
        {
            "Number": "1234567/11/2020/F",
            "Date": "2020-11-24T00:00:00.000000Z",
            "SellDate": "2021-03-23T00:00:00.000000Z",
            "GrossAmount": 22.34,
            "AmountToPay": 0.0,
            "Wear": 0.0,
            "WearKWH": 33.0,
            "PayingDeadlineDate": "2021-04-06T00:00:00.000000Z",
            "StartDate": "2021-01-23T00:00:00.000000Z",
            "EndDate": "2021-03-31T00:00:00.000000Z",
            "IsPaid": true,
            "IdPP": "1234567",
            "Type": "PPG",
            "TempType": "B",
            "DaysRemainingToDeadline": 0,
            "HasIban": true,
            "Iban": "ban",
            "Status": "Posted",
            "PdfExists": false,
            "IsInterestNote": false,
            "Color": "",
            "AgreementName": "",
            "AgreementNumber": "000/1990/00000/XX",
            "IsAdditionalAgreement": false,
            "AgreementEndDate": null,
            "AgreementExpired": false,
            "PDFPrintAllowed": true,
            "PaymentProcessAllowed": true,
            "AgreementHasCard": false,
            "AutomaticPaymentDate": "2021-04-04T00:00:00.000000Z",
            "IsInsurancePolicy": false,
            "IsLawyerAgreement": false,
            "IsPersonalSecurityAgreement": false
        },
        {
            "Number": "1234567/10/2020/F",
            "Date": "2020-11-24T00:00:00.000000Z",
            "SellDate": "2021-01-23T00:00:00.000000Z",
            "GrossAmount": 22.34,
            "AmountToPay": 0.0,
            "Wear": 0.0,
            "WearKWH": 33.0,
            "PayingDeadlineDate": "2021-02-08T00:00:00.000000Z",
            "StartDate": "2020-11-23T00:00:00.000000Z",
            "EndDate": "2021-01-31T00:00:00.000000Z",
            "IsPaid": true,
            "IdPP": "1234567",
            "Type": "PPG",
            "TempType": "B",
            "DaysRemainingToDeadline": 0,
            "HasIban": true,
            "Iban": "ban",
            "Status": "Posted",
            "PdfExists": false,
            "IsInterestNote": false,
            "Color": "",
            "AgreementName": "",
            "AgreementNumber": "000/1990/00000/XX",
            "IsAdditionalAgreement": false,
            "AgreementEndDate": null,
            "AgreementExpired": false,
            "PDFPrintAllowed": true,
            "PaymentProcessAllowed": true,
            "AgreementHasCard": false,
            "AutomaticPaymentDate": "2021-02-06T00:00:00.000000Z",
            "IsInsurancePolicy": false,
            "IsLawyerAgreement": false,
            "IsPersonalSecurityAgreement": false
        },
        {
            "Number": "1234567/9/2020/F",
            "Date": "2020-11-24T00:00:00.000000Z",
            "SellDate": "2020-11-23T00:00:00.000000Z",
            "GrossAmount": -156.55,
            "AmountToPay": 0.0,
            "Wear": 0.0,
            "WearKWH": 230.0,
            "PayingDeadlineDate": "2020-11-24T00:00:00.000000Z",
            "StartDate": "2019-11-14T00:00:00.000000Z",
            "EndDate": "2020-11-30T00:00:00.000000Z",
            "IsPaid": true,
            "IdPP": "1234567",
            "Type": "PPG",
            "TempType": "R",
            "DaysRemainingToDeadline": 0,
            "HasIban": true,
            "Iban": "ban",
            "Status": "Posted",
            "PdfExists": false,
            "IsInterestNote": false,
            "Color": "",
            "AgreementName": "",
            "AgreementNumber": "000/1990/00000/XX",
            "IsAdditionalAgreement": false,
            "AgreementEndDate": null,
            "AgreementExpired": false,
            "PDFPrintAllowed": true,
            "PaymentProcessAllowed": true,
            "AgreementHasCard": false,
            "AutomaticPaymentDate": "2020-11-22T00:00:00.000000Z",
            "IsInsurancePolicy": false,
            "IsLawyerAgreement": false,
            "IsPersonalSecurityAgreement": false
        }
    ],
    "Code": 0,
    "Message": null,
    "DisplayToEndUser": false,
    "EndUserMessage": null,
    "TokenExpireDate": "2022-10-01T14:37:41.854568Z",
    "TokenExpireDateUtc": "2022-10-01T12:37:41.854568Z"
}
```

Większość moich faktur jest prognozowana. Bardzo rzadko ktoś przychodzi obejrzeć licznik. Może dla prognoz zakładają zużycie w kWh i stąd brak zużycia w m3. Dodatkowym smaczkiem jest faktura na ujemną wartość (zwrot nadpłat).

**Comment by MG-Sky** [comment]
zazdroszczę minusowej faktury :⁠-⁠)
swoją drogą moje faktury wyglądaj identycznie, wygląda na to że pewnych danych nie podają

**Comment by pawelhulek** [comment]
Zamykam - nie jestem w stanie narazie nijak podratowac.
